#!/bin/sh

case "$1" in
	start)
		/usr/sbin/iptables-restore "/etc/mutab" &
		/opt/muos/script/system/startup.sh &
		;;
	stop)
		# It'd be nice to cleanly terminate the mux launcher and
		# background scripts, but for now, just make sure we don't
		# start duplicate mux processes on shutdown.
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
